name: Secret Scan

on:
  pull_request:
    branches:
      - main  # Trigger when PR targets main

jobs:
  trivy-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout PR branch
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.43.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.43.0_Linux-64bit.deb

      # Step 3: Run Trivy secret scan
      - name: Run Trivy Secret Scan
        run: |
          trivy fs --exit-code 1 --severity CRITICAL,HIGH --scanners secret .

